export interface WidgetNavEntry {
  id: string;
  label: string;
}

export const widgetCatalogMeta: WidgetNavEntry[] = [
  { id: "widget-approval-modal", label: "Approval modal" },
  { id: "widget-project-brief", label: "Project brief form" },
  { id: "widget-launch-progress", label: "Launch progress" },
  { id: "widget-upload-queue", label: "File upload" },
  { id: "widget-chat-panel", label: "Chat panel" },
  { id: "widget-invite-members", label: "Invite team members" },
  { id: "widget-team-directory", label: "Team list" },
  { id: "widget-settings-panel", label: "Settings panel" },
  { id: "widget-notification-feed", label: "Notifications feed" },
  { id: "widget-security-access", label: "Security & access" },
  { id: "widget-payment-methods", label: "Payment methods" },
  { id: "widget-activity-timeline", label: "Recent activity" },
  { id: "widget-command-palette", label: "Command palette" },
  { id: "widget-kanban-board", label: "Kanban board" },
  { id: "widget-event-scheduler", label: "Event scheduler" },
  { id: "widget-comment-thread", label: "Comment thread" },
  { id: "widget-plan-comparison", label: "Plan comparison" },
  { id: "widget-asset-review", label: "Asset review" },
  { id: "widget-api-keys", label: "API keys" },
  { id: "widget-support-queue", label: "Support queue" },
  { id: "widget-goal-tracker", label: "Goal tracker" },
  { id: "widget-integration-status", label: "Integration status" },
  { id: "widget-access-requests", label: "Access requests" },
  { id: "widget-license-activations", label: "License activations" },
  { id: "widget-experiment-results", label: "Experiment results" },
  { id: "widget-release-notes", label: "Release notes" },
  { id: "widget-analytics-overview", label: "Analytics overview" },
  { id: "widget-deals-pipeline", label: "Deals pipeline" },
  { id: "widget-billing-recovery", label: "Billing recovery" },
  { id: "widget-automation-runs", label: "Automation runs" },
  { id: "widget-audit-trail", label: "Audit trail" },
  { id: "widget-content-calendar", label: "Content calendar" },
  { id: "widget-incident-response", label: "Incident response" },
  { id: "widget-feedback-inbox", label: "Feedback inbox" },
  { id: "widget-revenue-snapshot", label: "Revenue snapshot" },
  { id: "widget-release-checklist", label: "Release checklist" },
  { id: "widget-team-pulse", label: "Team pulse" },
  { id: "widget-billing-usage", label: "Billing usage" },
  { id: "widget-customer-health", label: "Customer health" },
  { id: "widget-incident-digest", label: "Incident digest" },
  { id: "widget-review-inbox", label: "Review inbox" },
  { id: "widget-quick-actions", label: "Quick actions" },
];
